export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#110400",
        "slate-900": "#0F172A",
        "on-error": "#690005",
        "background": "#131315",
        "secondary": "#7bd0ff",
        "surface-tint": "#c0c6de",
        "on-secondary-fixed-variant": "#004c69",
        "success-green": "#4ADE80",
        "surface-container": "#201f21",
        "surface-container-low": "#1b1b1d",
        "surface-variant": "#353436",
        "primary-fixed-dim": "#c0c6de",
        "neon-pink": "#F472B6",
        "on-background": "#e5e2e3",
        "on-secondary-fixed": "#001e2c",
        "neon-purple": "#C084FC",
        "surface-container-high": "#2a2a2b",
        "primary-container": "#020617",
        "neon-blue": "#38BDF8",
        "primary": "#c0c6de",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-fixed": "#151b2d",
        "on-primary": "#2a3043",
        "danger-red": "#F87171",
        "surface-container-highest": "#353436",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#7bd0ff",
        "tertiary-fixed": "#ffdbc8",
        "on-secondary-container": "#00374d",
        "on-surface": "#e5e2e3",
        "secondary-fixed": "#c4e7ff",
        "inverse-on-surface": "#303032",
        "on-tertiary-container": "#917260",
        "on-tertiary-fixed-variant": "#5b4131",
        "outline": "#909097",
        "on-secondary": "#00354a",
        "surface-dim": "#131315",
        "primary-fixed": "#dce1fb",
        "on-primary-container": "#72778d",
        "on-surface-variant": "#c6c6cd",
        "secondary-container": "#00a6e0",
        "on-tertiary": "#422b1d",
        "surface": "#131315",
        "surface-bright": "#39393a",
        "tertiary": "#e4bfaa",
        "outline-variant": "#46464c",
        "on-primary-fixed-variant": "#40465a",
        "tertiary-fixed-dim": "#e4bfaa",
        "inverse-surface": "#e5e2e3",
        "inverse-primary": "#585e73",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#2b170a",
        "deep-black": "#000000",
        "on-error-container": "#ffdad6",
        "warning-yellow": "#FACC15"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "terminal-height": "240px",
        "sidebar-width": "320px",
        "panel-padding": "20px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "code-sm": ["JetBrains Mono"]
      },
      fontSize: {
        "label-caps": ["10px", {"lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "code-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
